title: InsideForest Documentation
description: InsideForest: supervised clustering with interpretable regions.
remote_theme: just-the-docs/just-the-docs
search_enabled: true
sitemap: true
keywords: InsideForest, clustering, interpretable, regions, trees
