title: InsideForest Documentation
description: "InsideForest: supervised clustering with interpretable regions."
keywords: InsideForest, clustering, interpretable, regions, trees
baseurl: /InsideForest
url: https://insideforest.github.io
